#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/voleventd`

case "$1" in
  start)
    stat_busy "Starting Volume Event Daemon"
    [ -z "$PID" ] && /usr/sbin/voleventd &> /dev/null &
    if [ ! -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      add_daemon voleventd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Volume Event Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon voleventd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
